version: '3.7'

networks:
  zoo:
    external: true

services:
  cache:
    container_name: domain-name-service-redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass 5gthjjicCPr5wcliairk
    volumes:
      - domain-name-service-redis:/data
    networks:
      - zoo

volumes:
  domain-name-service-redis: